pod 'FMDB'
# pod 'FMDB/FTS'   # FMDB with FTS
# pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
# pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
# pod 'FMDB/SQLCipher'   # FMDB with SQLCipher

platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"

pod 'MJRefresh'

platform :ios, '6.0'
pod 'RESideMenu', '~> 4.0.7'

pod 'PKYStepper', '0.0.1'

pod 'MBProgressHUD', '~> 0.9.1'

pod 'SWTableViewCell', '~> 0.3.7'

pod ‘DLRadioButton’